// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xnzcgkivnzbucxejuyyj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhuemNna2l2bnpidWN4ZWp1eXlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwMTg4OTgsImV4cCI6MjA2MjU5NDg5OH0.jXPRRe-l9mZFGKra49jPgSF-lG0jdIXw0KICOQe_K2Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);